export const RECORD_SCAN_REQUEST = "RECORD_SCAN_REQUEST";
export const RECORD_SCAN_SUCCESS = "RECORD_SCAN_REQUEST";
export const RECORD_SCAN_FAILED = "RECORD_SCAN_FAILED";

export const GET_MY_SCANS_REQUEST = "GET_MY_SCANS_REQUEST";
export const GET_MY_SCANS_SUCCESS = "GET_MY_SCANS_SUCCESS";
export const GET_MY_SCANS_FAILED = "GET_MY_SCANS_FAILED";
