apiVersion: apps/v1
kind: Deployment
metadata:
  name: comoscanner-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: comoscanner
  template:
    metadata:
      labels:
        component: comoscanner
    spec:
      containers:
        - name: comoscanner
          image: abdulmuneer22/como-scanner:0.0.1
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              value: db-postgresql-blr1-27952-do-user-8364381-0.b.db.ondigitalocean.com
            - name: DB_PORT
              value: "25060"
            - name: DB_USERNAME
              value: gitmart
            - name: DB_PASSWORD
              value: AVNS_4mMbJe9NT3JXfOU
            - name: DB_NAME
              value: gitmart
            - name: DB_SECRET
              value: "secret-db-ca"
            - name: APPLICATION_PORT
              value: "3000"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
