apiVersion: apps/v1
kind: Deployment
metadata:
  name: comoscanner-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: comoscanner
  template:
    metadata:
      labels:
        component: comoscanner
    spec:
      containers:
        - name: comoscanner
          image: abdulmuneer22/como-scanner:0.0.1
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              value: ""
            - name: DB_PORT
              value: "25060"
            - name: DB_USERNAME
              value: ""
            - name: DB_PASSWORD
              value: ""
            - name: DB_NAME
              value: ""
            - name: DB_SECRET
              value: ""
            - name: APPLICATION_PORT
              value: "3000"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
